#ifndef __ACHIEVEMENTNOTIFIER_HOOKS_H__
#define __ACHIEVEMENTNOTIFIER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace AchievementNotifier_Origins {
	void(*sharedState)(AchievementNotifier*);
	void(*notifyAchievement)(AchievementNotifier*);
	void(*showNextAchievement)(AchievementNotifier*);
}
namespace AchievementNotifier_Hooks {
	void sharedState(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN19AchievementNotifier11sharedStateEv"), (void*)rep, (void**)&AchievementNotifier_Origins::sharedState); }
	void notifyAchievement(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN19AchievementNotifier17notifyAchievementEPKcS1_S1_b"), (void*)rep, (void**)&AchievementNotifier_Origins::notifyAchievement); }
	void showNextAchievement(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN19AchievementNotifier19showNextAchievementEv"), (void*)rep, (void**)&AchievementNotifier_Origins::showNextAchievement); }
}
#endif