#ifndef __ACHIEVEMENTBAR_HOOKS_H__
#define __ACHIEVEMENTBAR_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace AchievementBar_Origins {
	void(*create)(AchievementBar*);
}
namespace AchievementBar_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN14AchievementBar6createEPKcS1_S1_b"), (void*)rep, (void**)&AchievementBar_Origins::create); }
}
#endif