#ifndef __BOOMLISTVIEW_HOOKS_H__
#define __BOOMLISTVIEW_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace BoomListView_Origins {
	void(*getListCell)(BoomListView*);
	void(*cellForRowAtIndexPath)(BoomListView*);
	void(*numberOfRowsInSection)(BoomListView*);
	void(*didSelectRowAtIndexPath)(BoomListView*);
	void(*cellHeightForRowAtIndexPath)(BoomListView*);
	void(*loadCell)(BoomListView*);
	void(*setupList)(BoomListView*);
}
namespace BoomListView_Hooks {
	void getListCell(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12BoomListView11getListCellEPKc"), (void*)rep, (void**)&BoomListView_Origins::getListCell); }
	void cellForRowAtIndexPath(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12BoomListView21cellForRowAtIndexPathER11CCIndexPathP9TableView"), (void*)rep, (void**)&BoomListView_Origins::cellForRowAtIndexPath); }
	void numberOfRowsInSection(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12BoomListView21numberOfRowsInSectionEjP9TableView"), (void*)rep, (void**)&BoomListView_Origins::numberOfRowsInSection); }
	void didSelectRowAtIndexPath(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12BoomListView23didSelectRowAtIndexPathER11CCIndexPathP9TableView"), (void*)rep, (void**)&BoomListView_Origins::didSelectRowAtIndexPath); }
	void cellHeightForRowAtIndexPath(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12BoomListView27cellHeightForRowAtIndexPathER11CCIndexPathP9TableView"), (void*)rep, (void**)&BoomListView_Origins::cellHeightForRowAtIndexPath); }
	void loadCell(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12BoomListView8loadCellEP13TableViewCelli"), (void*)rep, (void**)&BoomListView_Origins::loadCell); }
	void setupList(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12BoomListView9setupListEv"), (void*)rep, (void**)&BoomListView_Origins::setupList); }
}
#endif