#ifndef __CCANIMATEDSPRITE_HOOKS_H__
#define __CCANIMATEDSPRITE_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace CCAnimatedSprite_Origins {
	void(*animationFinished)(CCAnimatedSprite*);
}
namespace CCAnimatedSprite_Hooks {
	void animationFinished(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16CCAnimatedSprite17animationFinishedEPKc"), (void*)rep, (void**)&CCAnimatedSprite_Origins::animationFinished); }
}
#endif