#ifndef __CCCIRCLEWAVE_HOOKS_H__
#define __CCCIRCLEWAVE_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace CCCircleWave_Origins {
	void(*create)(CCCircleWave*);
}
namespace CCCircleWave_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCCircleWave6createEfffb"), (void*)rep, (void**)&CCCircleWave_Origins::create); }
}
#endif