#ifndef __CCCONTENTLAYER_HOOKS_H__
#define __CCCONTENTLAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace CCContentLayer_Origins {
	void(*create)(CCContentLayer*);
}
namespace CCContentLayer_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN14CCContentLayer6createERKN7cocos2d10_ccColor4BEff"), (void*)rep, (void**)&CCContentLayer_Origins::create); }
}
#endif