#ifndef __CCMENUITEMTOGGLER_HOOKS_H__
#define __CCMENUITEMTOGGLER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace CCMenuItemToggler_Origins {
	void(*setSizeMult)(CCMenuItemToggler*);
	void(*create)(CCMenuItemToggler*);
	void(*toggle)(CCMenuItemToggler*);
}
namespace CCMenuItemToggler_Hooks {
	void setSizeMult(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN17CCMenuItemToggler11setSizeMultEf"), (void*)rep, (void**)&CCMenuItemToggler_Origins::setSizeMult); }
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN17CCMenuItemToggler6createEPN7cocos2d6CCNodeES2_PNS0_8CCObjectEMS3_FvS4_E"), (void*)rep, (void**)&CCMenuItemToggler_Origins::create); }
	void toggle(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN17CCMenuItemToggler6toggleEb"), (void*)rep, (void**)&CCMenuItemToggler_Origins::toggle); }
}
#endif