#ifndef __CCNODECONTAINER_HOOKS_H__
#define __CCNODECONTAINER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace CCNodeContainer_Origins {
	bool(*init)(CCNodeContainer*);
	void(*visit)(CCNodeContainer*);
	void(*create)(CCNodeContainer*);
}
namespace CCNodeContainer_Hooks {
	void init(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCNodeContainer4initEv"), (void*)rep, (void**)&CCNodeContainer_Origins::init); }
	void visit(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCNodeContainer5visitEv"), (void*)rep, (void**)&CCNodeContainer_Origins::visit); }
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCNodeContainer6createEv"), (void*)rep, (void**)&CCNodeContainer_Origins::create); }
}
#endif