#ifndef __CCSCROLLLAYEREXT_HOOKS_H__
#define __CCSCROLLLAYEREXT_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace CCScrollLayerExt_Origins {
	void(*preVisitWithClippingRect)(CCScrollLayerExt*);
	void(*postVisit)(CCScrollLayerExt*);
}
namespace CCScrollLayerExt_Hooks {
	void preVisitWithClippingRect(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16CCScrollLayerExt24preVisitWithClippingRectEN7cocos2d6CCRectE"), (void*)rep, (void**)&CCScrollLayerExt_Origins::preVisitWithClippingRect); }
	void postVisit(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16CCScrollLayerExt9postVisitEv"), (void*)rep, (void**)&CCScrollLayerExt_Origins::postVisit); }
}
#endif