#ifndef __CCSPRITEPLUS_HOOKS_H__
#define __CCSPRITEPLUS_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace CCSpritePlus_Origins {
	void(*setPosition)(CCSpritePlus*);
	void(*setRotation)(CCSpritePlus*);
	void(*initWithTexture)(CCSpritePlus*);
	void(*createWithSpriteFrame)(CCSpritePlus*);
	void(*initWithSpriteFrameName)(CCSpritePlus*);
	void(*setFlipX)(CCSpritePlus*);
	void(*setFlipY)(CCSpritePlus*);
	void(*setScale)(CCSpritePlus*);
	void(*setScaleX)(CCSpritePlus*);
	void(*setScaleY)(CCSpritePlus*);
}
namespace CCSpritePlus_Hooks {
	void setPosition(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus11setPositionERKN7cocos2d7CCPointE"), (void*)rep, (void**)&CCSpritePlus_Origins::setPosition); }
	void setRotation(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus11setRotationEf"), (void*)rep, (void**)&CCSpritePlus_Origins::setRotation); }
	void initWithTexture(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus15initWithTextureEPN7cocos2d11CCTexture2DE"), (void*)rep, (void**)&CCSpritePlus_Origins::initWithTexture); }
	void createWithSpriteFrame(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus21createWithSpriteFrameEPN7cocos2d13CCSpriteFrameE"), (void*)rep, (void**)&CCSpritePlus_Origins::createWithSpriteFrame); }
	void initWithSpriteFrameName(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus23initWithSpriteFrameNameEPKc"), (void*)rep, (void**)&CCSpritePlus_Origins::initWithSpriteFrameName); }
	void setFlipX(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus8setFlipXEb"), (void*)rep, (void**)&CCSpritePlus_Origins::setFlipX); }
	void setFlipY(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus8setFlipYEb"), (void*)rep, (void**)&CCSpritePlus_Origins::setFlipY); }
	void setScale(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus8setScaleEf"), (void*)rep, (void**)&CCSpritePlus_Origins::setScale); }
	void setScaleX(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus9setScaleXEf"), (void*)rep, (void**)&CCSpritePlus_Origins::setScaleX); }
	void setScaleY(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CCSpritePlus9setScaleYEf"), (void*)rep, (void**)&CCSpritePlus_Origins::setScaleY); }
}
#endif