#ifndef __CCTEXTINPUTNODE_HOOKS_H__
#define __CCTEXTINPUTNODE_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace CCTextInputNode_Origins {
	void(*refreshLabel)(CCTextInputNode*);
	void(*setAllowedChars)(CCTextInputNode*);
	void(*onClickTrackNode)(CCTextInputNode*);
	void(*setMaxLabelScale)(CCTextInputNode*);
	void(*setLabelPlaceholderColor)(CCTextInputNode*);
	void(*create)(CCTextInputNode*);
	void(*getString)(CCTextInputNode*);
	void(*setString)(CCTextInputNode*);
}
namespace CCTextInputNode_Hooks {
	void refreshLabel(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCTextInputNode12refreshLabelEv"), (void*)rep, (void**)&CCTextInputNode_Origins::refreshLabel); }
	void setAllowedChars(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCTextInputNode15setAllowedCharsESs"), (void*)rep, (void**)&CCTextInputNode_Origins::setAllowedChars); }
	void onClickTrackNode(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCTextInputNode16onClickTrackNodeEb"), (void*)rep, (void**)&CCTextInputNode_Origins::onClickTrackNode); }
	void setMaxLabelScale(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCTextInputNode16setMaxLabelScaleEf"), (void*)rep, (void**)&CCTextInputNode_Origins::setMaxLabelScale); }
	void setLabelPlaceholderColor(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCTextInputNode24setLabelPlaceholderColorEN7cocos2d10_ccColor3BE"), (void*)rep, (void**)&CCTextInputNode_Origins::setLabelPlaceholderColor); }
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCTextInputNode6createEffPKcS1_iS1_"), (void*)rep, (void**)&CCTextInputNode_Origins::create); }
	void getString(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCTextInputNode9getStringEv"), (void*)rep, (void**)&CCTextInputNode_Origins::getString); }
	void setString(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN15CCTextInputNode9setStringESs"), (void*)rep, (void**)&CCTextInputNode_Origins::setString); }
}
#endif