#ifndef __CREATORLAYER_HOOKS_H__
#define __CREATORLAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 1/7/2023

namespace CreatorLayer_Origins {
	void(*onMapPacks)(CreatorLayer*);
	void(*onMyLevels)(CreatorLayer*);
	void(*onChallenge)(CreatorLayer*);
	void(*onGauntlets)(CreatorLayer*);
	void(*onDailyLevel)(CreatorLayer*);
	void(*onFameLevels)(CreatorLayer*);
	void(*onSavedLevels)(CreatorLayer*);
	void(*onSecretVault)(CreatorLayer*);
	void(*onWeeklyLevel)(CreatorLayer*);
	void(*keyBackClicked)(CreatorLayer*);
	void(*onLeaderboards)(CreatorLayer*);
	void(*onOnlineLevels)(CreatorLayer*);
	void(*onTreasureRoom)(CreatorLayer*);
	void(*onFeaturedLevels)(CreatorLayer*);
	void(*onOnlyFullVersion)(CreatorLayer*);
	bool(*init)(CreatorLayer*);
	void(*onBack)(CreatorLayer*);
}
namespace CreatorLayer_Hooks {
	void onMapPacks(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer10onMapPacksEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onMapPacks); }
	void onMyLevels(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer10onMyLevelsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onMyLevels); }
	void onChallenge(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer11onChallengeEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onChallenge); }
	void onGauntlets(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer11onGauntletsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onGauntlets); }
	void onDailyLevel(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer12onDailyLevelEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onDailyLevel); }
	void onFameLevels(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer12onFameLevelsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onFameLevels); }
	void onSavedLevels(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer13onSavedLevelsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onSavedLevels); }
	void onSecretVault(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer13onSecretVaultEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onSecretVault); }
	void onWeeklyLevel(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer13onWeeklyLevelEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onWeeklyLevel); }
	void keyBackClicked(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer14keyBackClickedEv"), (void*)rep, (void**)&CreatorLayer_Origins::keyBackClicked); }
	void onLeaderboards(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer14onLeaderboardsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onLeaderboards); }
	void onOnlineLevels(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer14onOnlineLevelsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onOnlineLevels); }
	void onTreasureRoom(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer14onTreasureRoomEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onTreasureRoom); }
	void onFeaturedLevels(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer16onFeaturedLevelsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onFeaturedLevels); }
	void onOnlyFullVersion(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer17onOnlyFullVersionEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onOnlyFullVersion); }
	void init(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer4initEv"), (void*)rep, (void**)&CreatorLayer_Origins::init); }
	void onBack(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12CreatorLayer6onBackEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&CreatorLayer_Origins::onBack); }
}
#endif