#ifndef __CUSTOMLISTVIEW_HOOKS_H__
#define __CUSTOMLISTVIEW_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace CustomListView_Origins {
	void(*getListCell)(CustomListView*);
	void(*create)(CustomListView*);
	void(*loadCell)(CustomListView*);
	void(*setupList)(CustomListView*);
}
namespace CustomListView_Hooks {
	void getListCell(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN14CustomListView11getListCellEPKc"), (void*)rep, (void**)&CustomListView_Origins::getListCell); }
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN14CustomListView6createEPN7cocos2d7CCArrayEffi12BoomListType"), (void*)rep, (void**)&CustomListView_Origins::create); }
	void loadCell(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN14CustomListView8loadCellEP13TableViewCelli"), (void*)rep, (void**)&CustomListView_Origins::loadCell); }
	void setupList(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN14CustomListView9setupListEv"), (void*)rep, (void**)&CustomListView_Origins::setupList); }
}
#endif