#ifndef __GAMESTATSMANAGER_HOOKS_H__
#define __GAMESTATSMANAGER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace GameStatsManager_Origins {
	void(*sharedState)(GameStatsManager*);
	void(*collectReward)(GameStatsManager*);
	void(*getBaseCurrency)(GameStatsManager*);
	void(*checkAchievement)(GameStatsManager*);
	void(*storeRewardState)(GameStatsManager*);
	void(*registerRewardsFromItem)(GameStatsManager*);
	void(*setStat)(GameStatsManager*);
}
namespace GameStatsManager_Hooks {
	void sharedState(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameStatsManager11sharedStateEv"), (void*)rep, (void**)&GameStatsManager_Origins::sharedState); }
	void collectReward(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameStatsManager13collectRewardE12GJRewardTypeP12GJRewardItem"), (void*)rep, (void**)&GameStatsManager_Origins::collectReward); }
	void getBaseCurrency(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameStatsManager15getBaseCurrencyEibi"), (void*)rep, (void**)&GameStatsManager_Origins::getBaseCurrency); }
	void checkAchievement(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameStatsManager16checkAchievementEPKc"), (void*)rep, (void**)&GameStatsManager_Origins::checkAchievement); }
	void storeRewardState(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameStatsManager16storeRewardStateE12GJRewardTypeiiSs"), (void*)rep, (void**)&GameStatsManager_Origins::storeRewardState); }
	void registerRewardsFromItem(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameStatsManager23registerRewardsFromItemEP12GJRewardItem"), (void*)rep, (void**)&GameStatsManager_Origins::registerRewardsFromItem); }
	void setStat(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameStatsManager7setStatEPKci"), (void*)rep, (void**)&GameStatsManager_Origins::setStat); }
}
#endif