#ifndef __GAMESOUNDMANAGER_HOOKS_H__
#define __GAMESOUNDMANAGER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace GameSoundManager_Origins {
	void(*playBackgroundMusic)(GameSoundManager*);
	void(*stopBackgroundMusic)(GameSoundManager*);
}
namespace GameSoundManager_Hooks {
	void playBackgroundMusic(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameSoundManager19playBackgroundMusicESsbb"), (void*)rep, (void**)&GameSoundManager_Origins::playBackgroundMusic); }
	void stopBackgroundMusic(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16GameSoundManager19stopBackgroundMusicEv"), (void*)rep, (void**)&GameSoundManager_Origins::stopBackgroundMusic); }
}
#endif