#ifndef __GJGAMELEVEL_HOOKS_H__
#define __GJGAMELEVEL_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace GJGameLevel_Origins {
	void(*getCoinKey)(GJGameLevel*);
	void(*getSongName)(GJGameLevel*);
	void(*setAttempts)(GJGameLevel*);
	void(*getLengthKey)(GJGameLevel*);
	void(*savePercentage)(GJGameLevel*);
	void(*levelWasAltered)(GJGameLevel*);
	void(*getNormalPercent)(GJGameLevel*);
	void(*setNormalPercent)(GJGameLevel*);
	void(*lengthKeyToString)(GJGameLevel*);
	void(*levelWasSubmitted)(GJGameLevel*);
	void(*setNewNormalPercent)(GJGameLevel*);
	bool(*init)(GJGameLevel*);
	void(*create)(GJGameLevel*);
	void(*setDemon)(GJGameLevel*);
	void(*setJumps)(GJGameLevel*);
	void(*setStars)(GJGameLevel*);
	void(*canEncode)(GJGameLevel*);
}
namespace GJGameLevel_Hooks {
	void getCoinKey(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel10getCoinKeyEi"), (void*)rep, (void**)&GJGameLevel_Origins::getCoinKey); }
	void getSongName(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel11getSongNameEv"), (void*)rep, (void**)&GJGameLevel_Origins::getSongName); }
	void setAttempts(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel11setAttemptsEi"), (void*)rep, (void**)&GJGameLevel_Origins::setAttempts); }
	void getLengthKey(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel12getLengthKeyEi"), (void*)rep, (void**)&GJGameLevel_Origins::getLengthKey); }
	void savePercentage(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel14savePercentageEibiib"), (void*)rep, (void**)&GJGameLevel_Origins::savePercentage); }
	void levelWasAltered(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel15levelWasAlteredEv"), (void*)rep, (void**)&GJGameLevel_Origins::levelWasAltered); }
	void getNormalPercent(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel16getNormalPercentEv"), (void*)rep, (void**)&GJGameLevel_Origins::getNormalPercent); }
	void setNormalPercent(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel16setNormalPercentEi"), (void*)rep, (void**)&GJGameLevel_Origins::setNormalPercent); }
	void lengthKeyToString(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel17lengthKeyToStringEi"), (void*)rep, (void**)&GJGameLevel_Origins::lengthKeyToString); }
	void levelWasSubmitted(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel17levelWasSubmittedEv"), (void*)rep, (void**)&GJGameLevel_Origins::levelWasSubmitted); }
	void setNewNormalPercent(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel19setNewNormalPercentEi"), (void*)rep, (void**)&GJGameLevel_Origins::setNewNormalPercent); }
	void init(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel4initEv"), (void*)rep, (void**)&GJGameLevel_Origins::init); }
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel6createEPN7cocos2d12CCDictionaryEb"), (void*)rep, (void**)&GJGameLevel_Origins::create); }
	void setDemon(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel8setDemonEi"), (void*)rep, (void**)&GJGameLevel_Origins::setDemon); }
	void setJumps(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel8setJumpsEi"), (void*)rep, (void**)&GJGameLevel_Origins::setJumps); }
	void setStars(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel8setStarsEi"), (void*)rep, (void**)&GJGameLevel_Origins::setStars); }
	void canEncode(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJGameLevel9canEncodeEv"), (void*)rep, (void**)&GJGameLevel_Origins::canEncode); }
}
#endif