#ifndef __GJITEMICON_HOOKS_H__
#define __GJITEMICON_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace GJItemIcon_Origins {
	void(*create)(GJItemIcon*);
}
namespace GJItemIcon_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10GJItemIcon6createE10UnlockTypeiN7cocos2d10_ccColor3BES2_bbbS2_"), (void*)rep, (void**)&GJItemIcon_Origins::create); }
}
#endif