#ifndef __GJSEARCHOBJECT_HOOKS_H__
#define __GJSEARCHOBJECT_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace GJSearchObject_Origins {
	void(*create)(GJSearchObject*);
}
namespace GJSearchObject_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN14GJSearchObject6createE10SearchType"), (void*)rep, (void**)&GJSearchObject_Origins::create); }
}
#endif