#ifndef __GJUSERSCORE_HOOKS_H__
#define __GJUSERSCORE_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace GJUserScore_Origins {
	void(*isCurrentUser)(GJUserScore*);
	void(*mergeWithScore)(GJUserScore*);
	void(*create)(GJUserScore*);
}
namespace GJUserScore_Hooks {
	void isCurrentUser(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJUserScore13isCurrentUserEv"), (void*)rep, (void**)&GJUserScore_Origins::isCurrentUser); }
	void mergeWithScore(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJUserScore14mergeWithScoreEPS_"), (void*)rep, (void**)&GJUserScore_Origins::mergeWithScore); }
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN11GJUserScore6createEPN7cocos2d12CCDictionaryE"), (void*)rep, (void**)&GJUserScore_Origins::create); }
}
#endif