#ifndef __GMANAGER_HOOKS_H__
#define __GMANAGER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace GManager_Origins {
	void(*dataLoaded)(GManager*);
	void(*encodeDataTo)(GManager*);
	void(*getSaveString)(GManager*);
	void(*save)(GManager*);
	void(*setup)(GManager*);
	void(*firstLoad)(GManager*);
}
namespace GManager_Hooks {
	void dataLoaded(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN8GManager10dataLoadedEP13DS_Dictionary"), (void*)rep, (void**)&GManager_Origins::dataLoaded); }
	void encodeDataTo(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN8GManager12encodeDataToEP13DS_Dictionary"), (void*)rep, (void**)&GManager_Origins::encodeDataTo); }
	void getSaveString(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN8GManager13getSaveStringEv"), (void*)rep, (void**)&GManager_Origins::getSaveString); }
	void save(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN8GManager4saveEv"), (void*)rep, (void**)&GManager_Origins::save); }
	void setup(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN8GManager5setupEv"), (void*)rep, (void**)&GManager_Origins::setup); }
	void firstLoad(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN8GManager9firstLoadEv"), (void*)rep, (void**)&GManager_Origins::firstLoad); }
}
#endif