#ifndef __LEVELEDITORLAYER_HOOKS_H__
#define __LEVELEDITORLAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace LevelEditorLayer_Origins {
	void(*removeObject)(LevelEditorLayer*);
	void(*addObjectFromString)(LevelEditorLayer*);
}
namespace LevelEditorLayer_Hooks {
	void removeObject(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16LevelEditorLayer12removeObjectEP10GameObjectb"), (void*)rep, (void**)&LevelEditorLayer_Origins::removeObject); }
	void addObjectFromString(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN16LevelEditorLayer19addObjectFromStringESs"), (void*)rep, (void**)&LevelEditorLayer_Origins::addObjectFromString); }
}
#endif