#ifndef __LEVELINFOLAYER_HOOKS_H__
#define __LEVELINFOLAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace LevelInfoLayer_Origins {
	void(*create)(LevelInfoLayer*);
}
namespace LevelInfoLayer_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN14LevelInfoLayer6createEP11GJGameLevel"), (void*)rep, (void**)&LevelInfoLayer_Origins::create); }
}
#endif