#ifndef __LOADINGLAYER_HOOKS_H__
#define __LOADINGLAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace LoadingLayer_Origins {
	void(*create)(LoadingLayer*);
}
namespace LoadingLayer_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12LoadingLayer6createEb"), (void*)rep, (void**)&LoadingLayer_Origins::create); }
}
#endif