#ifndef __MENULAYER_HOOKS_H__
#define __MENULAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace MenuLayer_Origins {
	void(*onFacebook)(MenuLayer*);
	void(*onEveryplay)(MenuLayer*);
	void(*onMoreGames)(MenuLayer*);
	void(*onMyProfile)(MenuLayer*);
	void(*onFreeLevels)(MenuLayer*);
	void(*onGameCenter)(MenuLayer*);
	void(*onNewgrounds)(MenuLayer*);
	void(*onFullVersion)(MenuLayer*);
	void(*keyBackClicked)(MenuLayer*);
	void(*onAchievements)(MenuLayer*);
	void(*onOptionsInstant)(MenuLayer*);
	void(*onGooglePlayGames)(MenuLayer*);
	void(*googlePlaySignedIn)(MenuLayer*);
	bool(*init)(MenuLayer*);
	void(*node)(MenuLayer*);
	void(*scene)(MenuLayer*);
	void(*onPlay)(MenuLayer*);
	void(*onQuit)(MenuLayer*);
	void(*keyDown)(MenuLayer*);
	void(*onDaily)(MenuLayer*);
	void(*onStats)(MenuLayer*);
	void(*onGarage)(MenuLayer*);
	void(*onRobTop)(MenuLayer*);
	void(*onCreator)(MenuLayer*);
	void(*onOptions)(MenuLayer*);
	void(*onTrailer)(MenuLayer*);
	void(*onTwitter)(MenuLayer*);
	void(*onYouTube)(MenuLayer*);
}
namespace MenuLayer_Hooks {
	void onFacebook(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer10onFacebookEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onFacebook); }
	void onEveryplay(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer11onEveryplayEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onEveryplay); }
	void onMoreGames(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer11onMoreGamesEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onMoreGames); }
	void onMyProfile(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer11onMyProfileEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onMyProfile); }
	void onFreeLevels(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer12onFreeLevelsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onFreeLevels); }
	void onGameCenter(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer12onGameCenterEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onGameCenter); }
	void onNewgrounds(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer12onNewgroundsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onNewgrounds); }
	void onFullVersion(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer13onFullVersionEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onFullVersion); }
	void keyBackClicked(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer14keyBackClickedEv"), (void*)rep, (void**)&MenuLayer_Origins::keyBackClicked); }
	void onAchievements(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer14onAchievementsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onAchievements); }
	void onOptionsInstant(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer16onOptionsInstantEv"), (void*)rep, (void**)&MenuLayer_Origins::onOptionsInstant); }
	void onGooglePlayGames(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer17onGooglePlayGamesEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onGooglePlayGames); }
	void googlePlaySignedIn(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer18googlePlaySignedInEv"), (void*)rep, (void**)&MenuLayer_Origins::googlePlaySignedIn); }
	void init(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer4initEv"), (void*)rep, (void**)&MenuLayer_Origins::init); }
	void node(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer4nodeEv"), (void*)rep, (void**)&MenuLayer_Origins::node); }
	void scene(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer5sceneEb"), (void*)rep, (void**)&MenuLayer_Origins::scene); }
	void onPlay(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer6onPlayEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onPlay); }
	void onQuit(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer6onQuitEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onQuit); }
	void keyDown(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer7keyDownEN7cocos2d12enumKeyCodesE"), (void*)rep, (void**)&MenuLayer_Origins::keyDown); }
	void onDaily(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer7onDailyEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onDaily); }
	void onStats(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer7onStatsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onStats); }
	void onGarage(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer8onGarageEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onGarage); }
	void onRobTop(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer8onRobTopEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onRobTop); }
	void onCreator(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer9onCreatorEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onCreator); }
	void onOptions(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer9onOptionsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onOptions); }
	void onTrailer(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer9onTrailerEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onTrailer); }
	void onTwitter(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer9onTwitterEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onTwitter); }
	void onYouTube(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9MenuLayer9onYouTubeEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MenuLayer_Origins::onYouTube); }
}
#endif