#ifndef __MYLEVELSLAYER_HOOKS_H__
#define __MYLEVELSLAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 1/7/2023

namespace MyLevelsLayer_Origins {
	void(*keyBackClicked)(MyLevelsLayer*);
	void(*setupLevelBrowser)(MyLevelsLayer*);
	bool(*init)(MyLevelsLayer*);
	void(*onNew)(MyLevelsLayer*);
	void(*onBack)(MyLevelsLayer*);
}
namespace MyLevelsLayer_Hooks {
	void keyBackClicked(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN13MyLevelsLayer14keyBackClickedEv"), (void*)rep, (void**)&MyLevelsLayer_Origins::keyBackClicked); }
	void setupLevelBrowser(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN13MyLevelsLayer17setupLevelBrowserEv"), (void*)rep, (void**)&MyLevelsLayer_Origins::setupLevelBrowser); }
	void init(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN13MyLevelsLayer4initEv"), (void*)rep, (void**)&MyLevelsLayer_Origins::init); }
	void onNew(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN13MyLevelsLayer5onNewEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MyLevelsLayer_Origins::onNew); }
	void onBack(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN13MyLevelsLayer6onBackEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&MyLevelsLayer_Origins::onBack); }
}
#endif