#ifndef __PAUSELAYER_HOOKS_H__
#define __PAUSELAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace PauseLayer_Origins {
	void(*createToggleButton)(PauseLayer*);
}
namespace PauseLayer_Hooks {
	void createToggleButton(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer18createToggleButtonESsMN7cocos2d8CCObjectEFvPS1_EbPNS0_6CCMenuENS0_7CCPointE"), (void*)rep, (void**)&PauseLayer_Origins::createToggleButton); }
}
#endif