#ifndef __PAUSELAYER_HOOKS_H__
#define __PAUSELAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace PauseLayer_Origins {
	void(*onAutoRetry)(PauseLayer*);
	void(*onNormalMode)(PauseLayer*);
	void(*onProgressBar)(PauseLayer*);
	void(*keyBackClicked)(PauseLayer*);
	void(*onPracticeMode)(PauseLayer*);
	void(*onAutoCheckpoints)(PauseLayer*);
	void(*createToggleButton)(PauseLayer*);
	void(*musicSliderChanged)(PauseLayer*);
	bool(*init)(PauseLayer*);
	void(*onEdit)(PauseLayer*);
	void(*onHelp)(PauseLayer*);
	void(*onQuit)(PauseLayer*);
	void(*onTime)(PauseLayer*);
	void(*keyDown)(PauseLayer*);
	void(*onResume)(PauseLayer*);
	void(*onRestart)(PauseLayer*);
}
namespace PauseLayer_Hooks {
	void onAutoRetry(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer11onAutoRetryEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onAutoRetry); }
	void onNormalMode(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer12onNormalModeEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onNormalMode); }
	void onProgressBar(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer13onProgressBarEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onProgressBar); }
	void keyBackClicked(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer14keyBackClickedEv"), (void*)rep, (void**)&PauseLayer_Origins::keyBackClicked); }
	void onPracticeMode(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer14onPracticeModeEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onPracticeMode); }
	void onAutoCheckpoints(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer17onAutoCheckpointsEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onAutoCheckpoints); }
	void createToggleButton(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer18createToggleButtonESsMN7cocos2d8CCObjectEFvPS1_EbPNS0_6CCMenuENS0_7CCPointE"), (void*)rep, (void**)&PauseLayer_Origins::createToggleButton); }
	void musicSliderChanged(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer18musicSliderChangedEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::musicSliderChanged); }
	void init(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer4initEb"), (void*)rep, (void**)&PauseLayer_Origins::init); }
	void onEdit(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer6onEditEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onEdit); }
	void onHelp(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer6onHelpEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onHelp); }
	void onQuit(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer6onQuitEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onQuit); }
	void onTime(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer6onTimeEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onTime); }
	void keyDown(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer7keyDownEN7cocos2d12enumKeyCodesE"), (void*)rep, (void**)&PauseLayer_Origins::keyDown); }
	void onResume(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer8onResumeEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onResume); }
	void onRestart(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN10PauseLayer9onRestartEPN7cocos2d8CCObjectE"), (void*)rep, (void**)&PauseLayer_Origins::onRestart); }
}
#endif