#ifndef __PLAYEROBJECT_HOOKS_H__
#define __PLAYEROBJECT_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace PlayerObject_Origins {
	void(*pushButton)(PlayerObject*);
	void(*setVisible)(PlayerObject*);
	void(*flipGravity)(PlayerObject*);
	void(*releaseButton)(PlayerObject*);
	void(*incrementJumps)(PlayerObject*);
	void(*spiderTestJump)(PlayerObject*);
	void(*playBurstEffect)(PlayerObject*);
	void(*playerIsFalling)(PlayerObject*);
	void(*runRotateAction)(PlayerObject*);
	void(*isFlying)(PlayerObject*);
}
namespace PlayerObject_Hooks {
	void pushButton(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject10pushButtonE12PlayerButton"), (void*)rep, (void**)&PlayerObject_Origins::pushButton); }
	void setVisible(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject10setVisibleEb"), (void*)rep, (void**)&PlayerObject_Origins::setVisible); }
	void flipGravity(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject11flipGravityEbb"), (void*)rep, (void**)&PlayerObject_Origins::flipGravity); }
	void releaseButton(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject13releaseButtonE12PlayerButton"), (void*)rep, (void**)&PlayerObject_Origins::releaseButton); }
	void incrementJumps(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject14incrementJumpsEv"), (void*)rep, (void**)&PlayerObject_Origins::incrementJumps); }
	void spiderTestJump(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject14spiderTestJumpEb"), (void*)rep, (void**)&PlayerObject_Origins::spiderTestJump); }
	void playBurstEffect(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject15playBurstEffectEv"), (void*)rep, (void**)&PlayerObject_Origins::playBurstEffect); }
	void playerIsFalling(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject15playerIsFallingEv"), (void*)rep, (void**)&PlayerObject_Origins::playerIsFalling); }
	void runRotateAction(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject15runRotateActionEb"), (void*)rep, (void**)&PlayerObject_Origins::runRotateAction); }
	void isFlying(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN12PlayerObject8isFlyingEv"), (void*)rep, (void**)&PlayerObject_Origins::isFlying); }
}
#endif