#ifndef __PLAYLAYER_HOOKS_H__
#define __PLAYLAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace PlayLayer_Origins {
	void(*cameraMoveY)(PlayLayer*);
}
namespace PlayLayer_Hooks {
	void cameraMoveY(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9PlayLayer11cameraMoveYEfff"), (void*)rep, (void**)&PlayLayer_Origins::cameraMoveY); }
}
#endif