#ifndef __POINTNODE_HOOKS_H__
#define __POINTNODE_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace PointNode_Origins {
	void(*create)(PointNode*);
}
namespace PointNode_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9PointNode6createEN7cocos2d7CCPointE"), (void*)rep, (void**)&PointNode_Origins::create); }
}
#endif