#ifndef __SONGINFOLAYER_HOOKS_H__
#define __SONGINFOLAYER_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace SongInfoLayer_Origins {
	void(*create)(SongInfoLayer*);
}
namespace SongInfoLayer_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN13SongInfoLayer6createEi"), (void*)rep, (void**)&SongInfoLayer_Origins::create); }
}
#endif