#ifndef __TABLEVIEW_HOOKS_H__
#define __TABLEVIEW_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 10/7/2023

namespace TableView_Origins {
	void(*cellForRowAtIndexPath)(TableView*);
}
namespace TableView_Hooks {
	void cellForRowAtIndexPath(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN9TableView21cellForRowAtIndexPathER11CCIndexPath"), (void*)rep, (void**)&TableView_Origins::cellForRowAtIndexPath); }
}
#endif