#ifndef __TEXTAREA_HOOKS_H__
#define __TEXTAREA_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 3/7/2023

namespace TextArea_Origins {
	void(*create)(TextArea*);
}
namespace TextArea_Hooks {
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN8TextArea6createESsPKcffN7cocos2d7CCPointEfb"), (void*)rep, (void**)&TextArea_Origins::create); }
}
#endif