#ifndef __UPLOADACTIONPOPUP_HOOKS_H__
#define __UPLOADACTIONPOPUP_HOOKS_H__

#include <gd.h>
#include <dobby.h>
#include <dlfcn.h>

// Generated by macro 29/6/2023

namespace UploadActionPopup_Origins {
	void(*closePopup)(UploadActionPopup*);
	void(*showFailMessage)(UploadActionPopup*);
	void(*showSuccessMessage)(UploadActionPopup*);
	bool(*init)(UploadActionPopup*);
	void(*create)(UploadActionPopup*);
}
namespace UploadActionPopup_Hooks {
	void closePopup(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN17UploadActionPopup10closePopupEv"), (void*)rep, (void**)&UploadActionPopup_Origins::closePopup); }
	void showFailMessage(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN17UploadActionPopup15showFailMessageESs"), (void*)rep, (void**)&UploadActionPopup_Origins::showFailMessage); }
	void showSuccessMessage(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN17UploadActionPopup18showSuccessMessageESs"), (void*)rep, (void**)&UploadActionPopup_Origins::showSuccessMessage); }
	void init(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN17UploadActionPopup4initEP19UploadPopupDelegateSs"), (void*)rep, (void**)&UploadActionPopup_Origins::init); }
	void create(void* rep) { DobbyHook(dlsym(dlopen("libcocos2dcpp.so", RTLD_LAZY), "_ZN17UploadActionPopup6createEP19UploadPopupDelegateSs"), (void*)rep, (void**)&UploadActionPopup_Origins::create); }
}
#endif